### ISSUE TITLE
404s on prod build

### ISSUE THREAD

**Issue by zigomir** [lewebsimple/nuxt3-fullstack#1]
Hi! First, thanks for this awesome template and really well written post on dev.to!

I'm trying it out locally and am getting 404s when running prod build (`yarn build` + `yarn start`).
Do you maybe know, is this nuxt 3 bug or something in this repo?

Otherwise app works as expected.
Navigating to http://localhost:3000/login results in additional 404s and 

```
Listening on http://localhost:3000/
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
Error: Unknown input type "form" ("form_1")
```

Weirdly non of this isn't the case in development environment (`yarn dev`) so it's kinda hard to debug.

[edit]
Form related error can be fixed wrapping `FormKit` within `<ClientOnly>` – [ref](https://github.com/formkit/formkit/issues/81#issuecomment-1040728382)

**Comment by lewebsimple** [comment]
Are you experiencing this when running this repo or is this another project based on it? If so, could you provide a link to the repo?
I'm short on spare time these days but I'll update things (repo + articles) shortly.

**Comment by zigomir** [comment]
On this repo directly, I just re-checked, cloning it and doing `yarn start` + `yarn build`.

I get it. Off-topic: I discovered that removing FormKit and tailwind significantly speeds up build times. :)
p.s.: was looking for remix.run like stack with vue (I really like / prefer Vue 3 with script setup syntax over React).

**Comment by lewebsimple** [comment]
I could reproduce the error in production, it seems to work when navigating to the route though (i.e. refreshing the login page causes the 500).
It's definitely related to FormKit...

**Comment by lewebsimple** [comment]
Fixed it using the official `@formkit/nuxt` module, also refactored the FormKit / Tailwind CSS integration using `@formkit/tailwindcss`

**Comment by zigomir** [comment]
👍 thanks, this fixes the problem.
